### ISSUE TITLE
Mrs. White now Dr. Orchid

### ISSUE THREAD

**Issue by jason-costello** [gregstoll/cluesolver#9]
https://slate.com/human-interest/2016/07/clue-changes-out-mrs-white-a-housekeeper-for-dr-orchid-a-female-scientist.html

Easy initial fix, but thinking about adding custom card sets for various editions of clue.
https://www.ultraboardgames.com/clue/editions.php

They all seem to follow (the few I spot checked) six suspects, six weapons, and nine locations.  I'm a Go dev, never touched rust so I might be off base.  Thinking that there could be an conf file that gets read at startup and defines the card sets and cards in each set.  yaml, toml, json, etc...

Editions:
  - standard_mrs_white:
       locations:
         - ball_room
         - study
         - hall
         - lounge
         - dining_room
         - kitchen
         - conservatory
         - billiard_room
         - library
       weapons:
         - knife
         - candlestick
         - recvolver
         - rpe
         - lead_pipe
         - wrench
       suspects:
         - col_mustard
         - prof_plumb
         - mr_green
         - miss_scarlet
         - miss_white
  - standard_dr_orchid:
       locations:
         - ball_room
         - study
         - hall
         - lounge
         - dining_room
         - kitchen
         - conservatory
         - billiard_room
         - library
       weapons:
         - knife
         - candlestick
         - recvolver
         - rpe
         - lead_pipe
         - wrench
       suspects:
         - col_mustard
         - prof_plumb
         - mr_green
         - miss_scarlet
         - dr_orchid

**Comment by gregstoll** [comment]
Oh, thanks, I didn't reailze that!

I can do the initial fix in Rust and JavaScript. I like the idea of having different editions, and I think that could all be done at the JavaScript layer.  I'll spin off a separate issue for that.
